### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by damianlluch** [agkayster/nextadmin-nextjs14-Fullstack-app#52]
Do you have any idea how to create an _app.tsx file in NextJS14 ? I haven't found a document and I need to define a provider for web3-react.js ?

Thanks

**Comment by agkayster** [comment]
Hey, I do not have an idea on how to create such but if I do, I will get it across to you.

**Comment by damianlluch** [comment]
I was able to do it, to add providers in Nextjs14 or 13, is through the layout.tsx file.

Best regards
